name: agyal
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization:
  sizer:
  firebase_core:
  firebase_auth:
  fluttertoast:
  shared_preferences:
  firebase_storage:
  cloud_firestore:
  device_preview:
  animated_splash_screen:
  introduction_screen:
  flutter_svg:
  smooth_page_indicator:
  modal_progress_hud_nsn:
  flutter_spinkit:
  google_fonts:
  font_awesome_flutter:
  country_code_picker:
  otp_text_field:
  provider:
  bottom_navy_bar:
  hexcolor: ^2.0.6
  badges:
  flutter_rating_bar:
  connectivity:
  flutter_bloc:
  bloc:
  one_context:
  google_sign_in:
  pixel_perfect:
  pin_code_fields:
  argon_buttons_flutter:

  circular_countdown_timer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: asset/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: asset/fonts/Tajawal/Tajawal-Black.ttf
        - asset: asset/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: asset/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: asset/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: asset/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: asset\fonts\Tajawal\Tajawal-Light.ttf
